version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
jobs:
  pulumi-update-dev:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: |
            npm install
            # npm run build
      - pulumi/update:
          stack: HuckStream/CircleCI-AWS-Pipeline/dev
  pulumi-update-prod:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: |
            npm install
            # npm run build
      - pulumi/update:
          stack: HuckStream/CircleCI-AWS-Pipeline/prod
workflows:
  pulumi:
    jobs:
      - pulumi-update-dev
        filters:
          branches:
            only:
              - dev
      - pulumi-update-prod
          filters:
            branches:
              only:
                - main
